# This file was generated by GoReleaser. DO NOT EDIT.
cask "gcal" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "207d11256327ed8452ab4c10e0d818d94da75e5af4e4999407cadc8b3627e425"
      url "https://github.com/tombridger1030/gcal/releases/download/v#{version}/gcal_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7b2c587f30eb4d6ab09c102db5f5b801b1dff54b7aaeff33be3942e41f656d76"
      url "https://github.com/tombridger1030/gcal/releases/download/v#{version}/gcal_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "gcal"
  desc "A tiny terminal Google Calendar pane for the side of your Mac screen."
  homepage "https://github.com/tombridger1030/gcal"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gcal"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gcal"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Drop your Google Cloud OAuth Desktop client JSON at:
      ~/Library/Application Support/gcal/credentials.json
    then run `gcal --login`.
    See https://github.com/tombridger1030/gcal#first-run-setup
  EOS
end
