# This file was generated by GoReleaser. DO NOT EDIT.
cask "gcal" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "930b2a75962681c9f4473f244954067ef2b95710efecf345b9908f651d0c8639"
      url "https://github.com/tombridger1030/gcal/releases/download/v#{version}/gcal_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f43f9a0aa28a5a28b8d4eae4797c26554a6c92ce5a7c2a394e1439f120b8c8da"
      url "https://github.com/tombridger1030/gcal/releases/download/v#{version}/gcal_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "gcal"
  desc "A tiny terminal Google Calendar pane for the side of your Mac screen."
  homepage "https://github.com/tombridger1030/gcal"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gcal"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gcal"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Drop your Google Cloud OAuth Desktop client JSON at:
      ~/Library/Application Support/gcal/credentials.json
    then run `gcal --login`.
    See https://github.com/tombridger1030/gcal#first-run-setup
  EOS
end
