# This file was generated by GoReleaser. DO NOT EDIT.
cask "gcal" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "e046fba4b6a703e258a6f3ac14e6ee178cbb1da127ff2a8b5936efa8ec2427e2"
      url "https://github.com/tombridger1030/gcal/releases/download/v#{version}/gcal_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "53ff5f8300fb4b546225d57e90846508f19fb84ff217a027d1d830aca05be4c4"
      url "https://github.com/tombridger1030/gcal/releases/download/v#{version}/gcal_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "gcal"
  desc "A tiny terminal Google Calendar pane for the side of your Mac screen."
  homepage "https://github.com/tombridger1030/gcal"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gcal"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gcal"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Drop your Google Cloud OAuth Desktop client JSON at:
      ~/Library/Application Support/gcal/credentials.json
    then run `gcal --login`.
    See https://github.com/tombridger1030/gcal#first-run-setup
  EOS
end
